// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hcfTW-DV2tJxBthN3ePjKugJb3EQS7c',
    appId: '1:139935682596:web:56d971d35ed8d766a788b1',
    messagingSenderId: '139935682596',
    projectId: 'streamflix-11477',
    authDomain: 'streamflix-11477.firebaseapp.com',
    storageBucket: 'streamflix-11477.appspot.com',
    measurementId: 'G-F8V1T8FNN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43OWdW93e3EvXvEZvIyutUTR3iUAzF5g',
    appId: '1:139935682596:android:d47e02527b73cd62a788b1',
    messagingSenderId: '139935682596',
    projectId: 'streamflix-11477',
    storageBucket: 'streamflix-11477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivE91I-K5247XFte_Md7kZvXYDe4eWnI',
    appId: '1:139935682596:ios:076f1d1d4c8e0093a788b1',
    messagingSenderId: '139935682596',
    projectId: 'streamflix-11477',
    storageBucket: 'streamflix-11477.appspot.com',
    iosBundleId: 'com.example.streamflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivE91I-K5247XFte_Md7kZvXYDe4eWnI',
    appId: '1:139935682596:ios:076f1d1d4c8e0093a788b1',
    messagingSenderId: '139935682596',
    projectId: 'streamflix-11477',
    storageBucket: 'streamflix-11477.appspot.com',
    iosBundleId: 'com.example.streamflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0hcfTW-DV2tJxBthN3ePjKugJb3EQS7c',
    appId: '1:139935682596:web:281c72bd0d0d3cf7a788b1',
    messagingSenderId: '139935682596',
    projectId: 'streamflix-11477',
    authDomain: 'streamflix-11477.firebaseapp.com',
    storageBucket: 'streamflix-11477.appspot.com',
    measurementId: 'G-6SPK5N691L',
  );
}
